projects:
  moodtracker:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: 5qvjby4myjcyfbcu6f7xsrev3m
      endpoints:
        prod: >-
          https://prpahrtw5zd75dljub62bpgjmy.appsync-api.us-east-1.amazonaws.com/graphql
